name: Webcom - Auto Assign Pull Requests

on:
  pull_request:
    branches:
      - env-webcom
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const assignees = ['jrul222'];
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: assignees,
            });
